version: "3.8"
services:
  api:    
    restart: always
    image: api
    build: .    
    ports:
      - "3000:3000"
    links: 
      - db
    volumes:
      - api:/build/src/
    
  db:
    container_name: mongo
    image: mongo
    ports:
     - '27017:27017'
    volumes:
      - db:/data/db
volumes:
  api:
  db:



